### ISSUE TITLE
UI: fourth list entry cut

### ISSUE THREAD

**Issue by Ninjiner** [Zren/plasma-applet-todolist#14]
I noticed, that every fourth entry in each list is somehow cutted at the top:
![ui-bug-todolist](https://user-images.githubusercontent.com/29404715/52997977-53bdf080-3422-11e9-91ea-1a0af6c40d1a.png)
Is this a bug from the plugin?

**Comment by Zren** [comment]
Is your DPI or UI scaled?

**Comment by Ninjiner** [comment]
Except if my OS was in the mood to change it, I didn't alter the DPI or UI scaling.

**Comment by digitalethics** [comment]
@Ninjiner Are you able to reproduce the issue and provide instructions?

**Comment by Ninjiner** [comment]
Unfortunately, I have changed my environment since. So now, I am not able to reproduce this.
