### ISSUE TITLE
error running fresh debian 9

### ISSUE THREAD

**Issue by drbeco** [Zren/plasma-applet-todolist#16]
I have installed it and also `apt-get install plasma-widgets-addons`, but when trying to add the widget on desktop it shows:

```
Error loading QML file: file:///home/beco/.local/share/plasma/plasmoids/com.github.zren.todolist/contents/ui/main.qml:61:31: Type FullRepresentation unavailable
file:///home/beco/.local/share/plasma/plasmoids/com.github.zren.todolist/contents/ui/FullRepresentation.qml:51:4: Type NoteSection unavailable
file:///home/beco/.local/share/plasma/plasmoids/com.github.zren.todolist/contents/ui/NoteSection.qml:174:3: Type NoteListView unavailable
file:///home/beco/.local/share/plasma/plasmoids/com.github.zren.todolist/contents/ui/NoteListView.qml:19:12: Type TodoItemDelegate unavailable
file:///home/beco/.local/share/plasma/plasmoids/com.github.zren.todolist/contents/ui/TodoItemDelegate.qml:6:1: module "org.kde.plasma.components" version 3.0 is not installed
```

Thanks

**Comment by Zren** [comment]
Debian stable has KDE Frameworks 5.28.0

https://repology.org/project/plasma-framework/versions

I don't support stuff that old. I try to keep the last Ubuntu 18.04 LTS in mind for the current version, but Debian that version of frameworks was released 2.5 year old ago.

You're free to install an older version of the widget and try that.

https://github.com/Zren/plasma-applet-todolist/releases

It's currently installed to `~/.local/share/plasma/plasmoids/com.github.zren.todolist/` like it says in those errors. So after you unzip an older version of the widget, copy the contents of the "package" folder to that folder (make sure the `metadata.desktop` is in the right place).

To test if the older version worked without restarting Plasma, run the command:

```
plasmawindowed com.github.zren.todolist
```

**Comment by drbeco** [comment]
Thanks, I appreciate the reply. I'll try to install the older version of todolist. If anything, I'll report back here, even if just to say it hopefully worked.

**Comment by Zren** [comment]
You know, I don't think I'm actually using that import yet actually. I think It was only added for testing PlasmaComponents 3.

https://github.com/Zren/plasma-applet-todolist/blame/master/package/contents/ui/TodoItemDelegate.qml#L6

You might be able to get away with deleting that import line from the current version.

**Comment by drbeco** [comment]
It actually worked! 

Not sure if we will see collateral effects, but for now it is doing fine.

Thanks!
