### ISSUE TITLE
Pressing the tab button shortens the text area size and I can't undo it 

### ISSUE THREAD

**Issue by ishank-dev** [Zren/plasma-applet-todolist#23]
If I press the tab button on the keyboard it shifts the text area and there is no way I can undo it.
![Screenshot_20200301_134006](https://user-images.githubusercontent.com/45262592/75622100-bd8ae180-5bc2-11ea-9b77-93ee156d1951.png)

**Comment by Zren** [comment]
`Shift+Tab` will un-indent.

**Comment by ishank-dev** [comment]
Thank you :+1: 
are there other such shortcuts too?
