### ISSUE TITLE
Notifications?

### ISSUE THREAD

**Issue by flaviusbuffon** [Zren/plasma-applet-todolist#26]
can it notify me ?
i hope this function will have
thanks
my email:jczhang@live.it

**Comment by Zren** [comment]
Notifications? No... The todolist widget is just a fancy text editor.

**Comment by flaviusbuffon** [comment]
Alright,but why don’t try it?
Users can set a time to notify them ,and then they can organize their time better！
I think it‘s greet

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Zren** [comment]
You want an alarm, or a full fledged calendar. Both are out of the scope of this widget.

Install `gnome-todo` if you want scheduled tasks, but I don't think it sends notifications.

**Comment by flaviusbuffon** [comment]
Ok but can you recommend me an application about “to do list” in kde manjaro?

Thanks

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by digitalethics** [comment]
@flaviusbuffon Please try to keep your next posts on GitHub clean and focused and do not include unnecessary data from your email. Thank you! Regarding your question: Try [Gnome ToDo](https://gitlab.gnome.org/GNOME/gnome-todo) or [Getting Things Gnome!](https://github.com/getting-things-gnome/gtg). Both are currently in development and should be released shortly. Alternatively, you can use TodoList together with [Fokus](https://store.kde.org/p/1308861/) and use the timer-based notification function for your tasks there.
