### ISSUE TITLE
Add changelog and commit difference for new releases

### ISSUE THREAD

**Issue by digitalethics** [Zren/plasma-applet-todolist#36]
Concerning future release practices, could you add a changelog and commit count for new releases? This would be helpful for distribution maintainers who want to make your widget part of the default install (instead of having users install it separately via the Plasma widget search) and to quickly identify and track updates.

**Comment by Zren** [comment]
All my widgets have a changelog. You can compare tags for individual comits.

* https://github.com/Zren/plasma-applet-todolist/blob/master/ChangeLog.md
* https://github.com/Zren/plasma-applet-todolist/compare/v10...v11

**Comment by digitalethics** [comment]
Yeah, but I meant here: 

![releases](https://user-images.githubusercontent.com/57445091/80872728-1c98cf80-8cb4-11ea-8c9c-b60b87ea631f.png)

**Comment by digitalethics** [comment]
@Zren Would you mind including the changelog above the assets in the release section?

**Comment by Zren** [comment]
No. I copy the changelog to https://store.kde.org already which is where it's actually visible to users. The releases text is a GitHub only feature anyways.
