### ISSUE TITLE
Replace "Configure ToDoList..." with "ToDoList Settings" or vice versa

### ISSUE THREAD

**Issue by digitalethics** [Zren/plasma-applet-todolist#38]
The context menu entry "Configure ToDoList..." doesn't linguistically match the title of the following window named "ToDoList Settings". This is rather a problem with Plasma widgets in general as this issue affects all of them. 

_This is part of a planned series on UI suggestions and an effort to make the Plasma desktop environment more accessible and easier to use for newcomers._

**Comment by Zren** [comment]
Consistency with other widgets is better.

**Comment by digitalethics** [comment]
> Consistency with other widgets is better.

Agreed.
