### ISSUE TITLE
Overlay task count number is not showing

### ISSUE THREAD

**Issue by felihommen** [Zren/plasma-applet-todolist#4]
Icon overlay that shows the number of incomplete tasks is not shown.
When I add or remove a list, then this number is showing and working well until I close desktop session. Then, when I login again, number of task is not shown. If number of tasks icon is not shown, then adding or removing tasks makes no difference. Only adding or removing lists makes it work

Using Kubuntu 18.04

**Comment by anoopv511** [comment]
Same issue. Using Kubuntu 18.04.

**Comment by Zren** [comment]
Fixed in v8
