### ISSUE TITLE
Add labels to this repository

### ISSUE THREAD

**Issue by digitalethics** [Zren/plasma-applet-todolist#42]
I'm going to review your todolist widget a bit more intensively in the coming days and weeks and it would be very helpful for me if you make more active use of labels in this repository. This would give me a more immediate feedback regarding what features you would consider implementing and which ones are out of scope for this project. I'd also like to get more involved in playing around with ideas and conceptual design for this widget. Would there be a possibility to give me access to be able to create new labels and to assign them to issues in this repo?

**Comment by Zren** [comment]
I made you a collaborator so you can manage labels. Don't push code or I'll just force push to overwrite it.

**Comment by digitalethics** [comment]
> I made you a collaborator so you can manage labels.

Thanks a lot! 

> Don't push code or I'll just force push to overwrite it.

Noted.

**Comment by digitalethics** [comment]
@Zren I've finished the initial review, went through the entire issue list and have attached labels and a v13 milestone of issues that I think should be prioritized (bugs first, usability issues second, enhancements third). Do you want me to wait until v13 is out to start with a more thorough brainstorming for potential new features and the development of the user interface?
