### ISSUE TITLE
Interact with Event Calendar

### ISSUE THREAD

**Issue by digitalethics** [Zren/plasma-applet-todolist#54]
It would be a great to make widgets interact with one another to leverage the strengths of each tool and to strengthen the integration of the Plasma widget ecosystem as a whole. One such feature would be to add an option to send a task item from TDL to be displayed in the Event Calendar with a simple button click.

**Comment by Zren** [comment]
No. Eventually I will add synching + creating google tasks to eventcalendar, but I will never sync with a todo markdown file.
