### ISSUE TITLE
Is there any way of changing the icon that shows up on multiple instances of the TodoList widget?

### ISSUE THREAD

**Issue by rafaelmuynarsk** [Zren/plasma-applet-todolist#57]
I've followed this issue for creating multiple instances of the TodoList widget on my taskbar:

https://github.com/Zren/plasma-applet-todolist/issues/13

It worked perfectly, but now I'd like to change the default icon that shows on different intances of my tasks. It doesn't seem to be possible just by clicking on the configurations, is there a way of easily doing that by changing some lines of code like in the case of the last issue?

**Comment by Zren** [comment]
https://develop.kde.org/docs/plasma/widget/examples/#configurable-icon

**Comment by rafaelmuynarsk** [comment]
Thanks, I'm not very familiar with this structure of files though... I've tried making changes myself but I only managed to disappear with all the default configuration from the menu. Would you know what's the issue with the ConfigGeneral.qml like the following?

```
ConfigPage {
	id: page
	showAppletVersion: true

  property alias cfg_icon: configIcon.value

  Kirigami.FormLayout {
      anchors.left: parent.left
      anchors.right: parent.right

      ConfigIcon {
          id: configIcon
          Kirigami.FormData.label: i18nd("plasma_applet_org.kde.plasma.kickoff", "Icon:")
      }
  }


	ConfigSection {
		visible: plasmoid.location == PlasmaCore.Types.Floating

		ConfigCheckBox {
			configKey: 'hidden'
			text: i18n("Desktop Widget: Hide")
		}

		ConfigCheckBox {
			configKey: "showBackground"
			text: i18n("Desktop Widget: Show background")
		}
	}

	ConfigSection {
		Label {
			text: i18n("Completed Items")
			font.weight: Font.Bold
			font.pointSize: theme.defaultFont.pointSize * 1.25
		}

		ConfigCheckBox {
			configKey: 'deleteOnComplete'
			text: i18n("Delete On Complete")
		}

		ConfigCheckBox {
			configKey: 'strikeoutCompleted'
			text: i18n("Strikeout")
		}

		ConfigCheckBox {
			configKey: 'fadeCompleted'
			text: i18n("Faded")
		}
	}

	ConfigSection {
		Label {
			text: i18n("List Title Style")
			font.weight: Font.Bold
			font.pointSize: theme.defaultFont.pointSize * 1.25
		}

		ConfigCheckBox {
			id: listTitlePlasmaStyle
			configKey: "listTitlePlasmaStyle"
			text: i18n("Show text field background")
		}

		ConfigCheckBox {
			configKey: "listTitleBold"
			text: i18n("Bold")
		}

		ConfigCheckBox {
			enabled: !listTitlePlasmaStyle.checked
			configKey: "listTitleOutline"
			text: i18n("Show outline")
		}

	}
}
```
I only added the small piece off code from the tutorial but I think there's still some mistake in there.

**Comment by Zren** [comment]
I honestly have no clue how you managed that. It worked for me:

![2020-11-13___19-18-07](https://user-images.githubusercontent.com/416367/99132783-90158500-25e5-11eb-96d2-ee1241307798.png)

I've more time to work on it today now that eventcal is fixed, so might as well add the option since I wrote the tutorial anyways.
