### ISSUE TITLE
Alignment issues when placed in Top Panel

### ISSUE THREAD

**Issue by anoopv511** [Zren/plasma-applet-todolist#6]
When the widget is placed in top panel the items are added in the reverse direction, i.e from bottom to top. Attached screenshot showing the same. 
![image](https://user-images.githubusercontent.com/16700489/44810936-eeb2dc00-abf0-11e8-8c98-bd3cf7ef3b65.png)

**Comment by Zren** [comment]
https://github.com/Zren/plasma-applet-todolist/blob/master/package/contents/ui/NoteListView.qml#L15

```
verticalLayoutDirection: plasmoid.location == PlasmaCore.Types.TopEdge ? ListView.BottomToTop : ListView.TopToBottom
```

Ooops, I got the logic reversed when I wrote it.

**Comment by anoopv511** [comment]
I'm a noob in Qt Development, so having hard time fixing this. Would be great if you could close this issue as soon as you can. :)

**Comment by Zren** [comment]
Yep, check for a new version tonight or tomorrow, going through the backlog of other TodoList stuff before releasing an update.

**Comment by Zren** [comment]
Fixed in v8
