### ISSUE TITLE
Strikethrough

### ISSUE THREAD

**Issue by tichun** [Zren/plasma-applet-todolist#9]
It'd be fun to have strikethrough option for finished tasks, when these are not deleted.

**Comment by Zren** [comment]
`TextArea.font.strikeout` exists, so this was easy once I looked that up. Look forward to this in the next version once I add a config toggle.

-----

Note to self:

I first tried wrapping the rendered text in `<s></s>` during `renderText()` and triggered `updateText()` after toggling `setCompleted()`. For some reason, that somehow made the text permanently strikethrough even when in editing mode...

```
qml: updateText isEditing=false
qml: renderText
qml:     tesdffstte sdf<br><a href="https://google.com">https://google.com</a> 
qml:     <s>tesdffstte sdf<br><a href="https://google.com">https://google.com</a> </s>
qml: updateText isEditing=true
qml: updateText isEditing=false
qml: renderText
qml:     
qml:     
qml: updateText isEditing=false
qml: renderText
qml:     tesdffstte sdf<br><a href="https://google.com">https://google.com</a> 
qml:     <s>tesdffstte sdf<br><a href="https://google.com">https://google.com</a> </s>
```

![2019-03-13___16-50-56](https://user-images.githubusercontent.com/416367/54314038-fa745780-45b0-11e9-9bb2-da29c1e701a7.png)

It's possible that it might be getting called twice due `textArea.text` having a binding to `todoItemDelegate.isCompleted` somehow.

**Comment by Zren** [comment]
I'll also be fading the completed items by default too (it's optional).

![2019-03-13___19-26-53](https://user-images.githubusercontent.com/416367/54321402-65c92400-45c7-11e9-9461-57f0eb851b2e.png)

**Comment by Zren** [comment]
v11 with this has been released.
